### ISSUE TITLE
[REFACTOR] 비밀번호 암호화

### ISSUE THREAD

**Issue by zangsu** [woowacourse-teams/2024-code-zap#579]
## 📌 어떤 기능을 리팩터링 하나요?
> 사용자 비밀번호를 암호화 하여 저장한다.

## AS-IS
사용자 비밀번호 평문 저장

## TO-BE
- [x] 사용자의 비밀번호를 단방향 암호화를 적용한다.
- [x] DB에 저장되어 있는 비밀번호를 암호화한다.
- [x] 회원가입시 salt 문자열을 생성해 저장한다.
- [x] 기존 회원들의 salt 문자열 필드를 추가한다.
- [x] 로그인을 확인할 때 암호화를 하여 비교한다.

## Task

- [x] #585 
- [x] #584 
- [x] #586 

## ⏳ 예상 소요 시간
> 1일 (~ 9/4)

**Comment by zangsu** [comment]
# 암호화를 하는 이유

> "개인정보처리자"란 업무를 목적으로 개인정보파일을 운용하기 위하여 스스로 또는 다른 사람을 통하여 개인정보를 처리하는 공공기관, 법인, 단체 및 개인 등을 말한다’라고 한다. 

개인정보처리자는 사업자 등록 여부와 관련이 없이 업무를 목적으로 개인의 정보를 다루는 대상을 말합니다.
이에 코드잽 역시 개인정보처리자에 해당하며, 개인정보의 안전성 확보조치 기준 7조에 명시된 대로 비밀번호를 일방향 암호화 하여야 합니다.

## 참고 자료

[(개인정보보호위원회) 개인정보의 안전성 확보조치 기준](https://www.law.go.kr/LSW//admRulLsInfoP.do?admRulId=73493&efYd=0#J7-0:0) - 7조 2항

[[법령] 개인정보의 암호화 조치 안내서(2020.12.개정)](https://www.cela.kr/4/?q=YToyOntzOjEyOiJrZXl3b3JkX3R5cGUiO3M6MzoiYWxsIjtzOjQ6InBhZ2UiO2k6MTt9&bmode=view&idx=5596553&t=board)

[개인정보 보호법 해석 사례집 1.0](https://www.pipc.go.kr/np/cop/bbs/selectBoardArticle.do?bbsId=BS217&mCode=D010030000&nttId=10299#LINK) -> 첨부파일 p.48

**Comment by zangsu** [comment]
## 사용 알고리즘 및 암호화 방법

[개인정보의 안전성 확보조치 기준] 제7조에 따라 비밀번호는 일방향 (해시함수) 암호화를 사용해야 합니다.

### 사용 알고리즘

국가사이버안보센터의 검증대상 알고리즘 중 일방향 암호화 알고리즘은 다음이 존재합니다. 
- SHA-2 (SHA-224/256/384/512)
- LSH (LSH-224/256/384/512/512-224/512-256)
- SHA-3 (SHA3-224/256/384/512)

[국가사이버안보센터 - 검증대상 알고리즘](https://www.ncsc.go.kr:4018/PageLink.do?link=forward:/PageContent.do&tempParam1=&menuNo=060000&subMenuNo=060200&thirdMenuNo=)

이 중 사용 레퍼런스를 쉽게 찾을 수 있는 SHA-2 알고리즘을 사용해 암호화를 진행합니다.

**Comment by zangsu** [comment]
## SALT

해시함수 특성상 동일한 비밀번호를 가지고 있는 여러 사용자는 모두 비밀번호가 같은 해시값을 가지게 됩니다.
즉, 같은 해시값을 가지고 있는 사용자 끼리는 서로의 비밀번호를 유추할 수 있는 것인데요. 

이를 방지하기 위해 비밀번호를 암호화 할 때 특정 문자열을 붙여 함께 암호화를 할 수 있고, 이 방법을 salting 이라고 합니다.

### 사용 방법

회원 id 와 salt 문자열을 1:1 연관관계를 가지도록 구현합니다. 
모든 회원은 회원가입시 랜덤으로 생성되는 salt 문자열과 연관관계가 생성됩니다.

**Comment by zangsu** [comment]
## 도입 방법

배포되어 있는 서비스에 암호화 및 Salt 값 추가가 필요한 상황입니다. 
즉, 이미 회원가입이 되어 있는 사용자의 정보를 수정 / 추가 해 주어야 합니다. 

고려했던 방법은 다음과 같습니다. 
1. 특정 사용자가 로그인을 하는 시점에 암호화가 되어 있지 않으면 암호화, Salt 값 추가
2. 특정 시간에 서비스 전체 중지 후 암호화 작업

1번 방법이 서비스를 중단하지 않기에 이상적이지만, 서비스 배포 이전에 모든 사용자의 비밀번호가 암호화 되어 있어야 하기 때문에 실제로 적용하기 어렵습니다. 
따라서 사용자가 적을 것으로 예상되는 시점에 잠시 서비스를 중단 후 점검해야 할 것 같습니다.

## FE 요청 사항 
@Jaymyong66 @vi-wolhwa @Hain-tain 
앞으로도 가끔 서비스 점검이 진행될 것 같은데요. 
이에 프론트 분들에게 "점검 페이지" 작업을 요청드립니다. 

의견이 있으면 Comment 로 달아주세요.

**Comment by jminkkk** [comment]
안녕하세요 짱수~  잘 정리해주신 거 읽었습니다.
제가 이해하기로는 비밀번호를 해당 방식으로 관리하게 되면, 
앞으로 salt 값, salt + 비밀번호로 암호화된 문자열 총 2개로 저장하여 관리한다고 이해했는데 맞을까요~?

---

> 회원 id 와 salt 문자열을 1:1 연관관계를 가지도록 구현합니다.

1:1 연관관계를 가지도록 한다는 것이 salt 문자열을 위한 테이블을 생성하는 걸까요~?

---

> 1번 방법이 서비스를 중단하지 않기에 이상적이지만, 서비스 배포 이전에 모든 사용자의 비밀번호가 암호화 되어 있어야 하기 때문에 실제로 적용하기 어렵습니다. 따라서 사용자가 적을 것으로 예상되는 시점에 잠시 서비스를 중단 후 점검해야 할 것 같습니다.

짱수가 얘기하는 암호화 작업이 생성된 기존 암호화 적용되지 않은 문자열에 대한 처리 같아요~
아직 정식 배포를 하지 않았고 회원이 적기 때문에 현재 회원들의 salt 값, salt + 비밀번호 값들을 데이터 스크립트, 기존 password 백업 파일을 작성해두고 새벽에 새 데이터 스크립트를 실행하면 어떨까요? 

이렇게 되면 굳이 중단을 하지 않고 적용할 수 있을 것 같은데 어떤가요~?

**Comment by zangsu** [comment]
@jminkkk 

> 앞으로 salt 값, salt + 비밀번호로 암호화된 문자열 총 2개로 저장하여 관리한다고 이해했는데 맞을까요~?
맞습니다!

> 1:1 연관관계를 가지도록 한다는 것이 salt 문자열을 위한 테이블을 생성하는 걸까요~?

맞습니다! 회원의 id 값을 외래키로 가지게 될 것 같아요.

> 이렇게 되면 굳이 중단을 하지 않고 적용할 수 있을 것 같은데 어떤가요~?

정식 배포가 아니기에 몰리가 말해준 방법으로 진행해도 좋아요. 
다만, 실제 배포시 고민을 해 보아야 하는 주제이니 저와 함께 누군가 병렬적으로 고민만 해 보아도 좋을 것 같습니다!

꼭 점검중 페이지를 띄우는 방향으로 고정시키기 보단, 빠른 시간 내에 적용이 어려울 경우 사용자가 적은 시간에 데이터 스크립트를 실행하도록 유연하게 가져가도 좋을 것 같네요
